// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added

var findTheDifference = function(s, t) {
    var objy={

    }

    for (let i = 0; i < s.length; i++) {
            if(Object.is(objy[s[i]],undefined)){
                objy[s[i]]=1
            }else{
                objy[s[i]]++
            }       
    }

    for (let i = 0; i < t.length; i++) {
        if(Object.is(objy[t[i]],undefined) || objy[t[i]]==0){
            return t[i]
        }else{
            objy[t[i]]--
        }        
    }

};


// Essentially we will be taking advantage of the Bitwise XOR ^ operator.
// For every **NUMBER**   X, we have  
// * **X^X=0**  
// and  
// * **X^0=X**

// So the **plan** is: 
// 	**1.** Iterate over the shortest array **s**
//    **2.** Keep accumulating (XOR ^ing) the elements of both s and t, after we have converted them to **Numbers** with CharCodeAt() so the XOR can work
//    **3.** Return the **converted back to character** final sum
   
 


var findTheDifference = function(s, t) {
    var sum=0 // initialize the accumulator
	
	// t.length < s.length because there will always be 1 extra letter on t (the one we want to return)
    for (var i = 0; i < s.length; i++) {
		sum^=                       // accumulate with XOR 
		t[i].charCodeAt()^          // the converted to Number t[i]
        s[i].charCodeAt()           // along with a converted to Number s[i],
                                    
    }
    sum^=t[i].charCodeAt()          // add the remaining letter of t
   return String.fromCharCode(sum)  // return the converted to Character total

};

var findTheDifference = function(s, t) {
    
   return String.fromCharCode(t.charCodeAt()-s.charCodeAt())  // return the converted to Character total

};





console.log(findTheDifference(
   "abcd" ,"abecd"
))

charCodeAt()
console.log(25^0)