// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added

var findTheDifference = function(s, t) {
    var objy={

    }

    for (let i = 0; i < s.length; i++) {
            if(objy.s[i]!=undefined){
                objy.s[i]=1
            }else{
                objy.s[i]++
            }       
    }

    for (let i = 0; i < t.length; i++) {
        if(objy.t[i]==undefined || objy.t[i]==0){
            return t[i]
        }else{
            objy.t[i]--
        }        
    }

};


console.log(findTheDifference(
   "abcd" ,"abcde"
))